
nelmio_api_doc:
    documentation:
#        servers:
#            - url: http://max4d.pro/
#              description: API over HTTP
        info:
            title: Company’s hierarchy
            description: Symfony backed test task
            version: "1"
#        components:
#            securitySchemes:
#                Bearer:
#                    type: http
#                    scheme: bearer
#                    bearerFormat: JWT
#        security:
#            - Bearer: []