version: "3.3"
services:

  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
      - /var/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  php-fpm:
    user: "1000:1000"
    image: webdevops/php-dev:7.4
    ports:
      - '9000:9000'
    hostname: php-fpm
    volumes:
      - "./:/app:rw"
    working_dir: "/app"
    depends_on:
      - pg_db

  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "80:80"
    volumes:
      - "./:/app"
    depends_on:
      - php-fpm